language: csharp
solution: Alt.Utils.sln
install:
  - nuget restore Alt.Utils.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild  /p:Configuration=Debug Alt.Utils.sln
  - ls
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./MaybeTests/bin/Debug/MaybeTests.dll
