language: csharp
solution: Alt.Utils.sln

 env:
  global:
   - secure: "wdcFsR47fVrfa36GC51hejG+Jb6cZJp0tudcDrVL1WXLqdSRPZJ3mxZLTFOkdD65LY2gxghbpjEDw/CdpBEav+trCQCt7xJAmn5Ee8RLWwEOeOSNzzcOh+nvakdQVOFr+1/rEqQK+lH0B7axkScVoMGq8rgO66TrZJ5o0g4QYS/EkvR9beDXKScILj72Q3jzAQMpGGcUIlraTEjMSgAODqu2xqlZdRLYgHYk8tWPEULMzCFZ9GYAz9Dna+GEPkRJLk0BzsooP2lAKGKfnUlvMFq2HNDSpaMb2x8xlleNst4j+ALkguk9RiCv7ZaFYVt5sTHwzE447w8KUqcYdfQH8wZbVECu35x6X6ghvwioAzK84a98V+w1xLGCVqRMnm1iVBcw6m+3pndJ789DNa6gEfAI54ofnkGUknsKhSPh2z52lvvWw1fAxytcsDxUc87YLJWf9LcNw38QQr2jcwUF9t1Gi1J8ReyvgJJnHWyCfHZ82y6KX3BdPa/A6POkjetpd49K604W7xw8c8itiF+6AMldBpynGcDuuHIeYFmJ7MQHqSjqcpsHT9lywsYW/Duvp3xVIRj83dj9aOJefeTBYXEnzZSiw9koptgO0INrKpP72umpj0ygbp0PnOHwA9s9gokQk3exYzpgNSIz/FFRR+5JNi1cIaa/6b3BHdYh00s="


addons:
  coverity_scan:
    project:
      name: "Altamir/Maybe"
      description: "implementação maybe"
    notification_email: altamir.benkenstein@outlook.com
    build_command_prepend: ""
    build_command: "msbuild  /p:Configuration=Debug Alt.Utils.sln"
    branch_pattern: master

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


install:
  - nuget restore Alt.Utils.sln
  - sudo apt-get install nunit-console  

script:
  - msbuild  /p:Configuration=Debug Alt.Utils.sln   
  - nunit-console ./MaybeTests/bin/Debug/MaybeTests.dll