language: csharp
solution: Alt.Utils.sln
install:
  - nuget restore Alt.Utils.sln
  - sudo apt-get install nunit-console  
script:
  - msbuild  /p:Configuration=Debug Alt.Utils.sln
  - ls 
  - nunit-console ./MaybeTests/bin/Debug/MaybeTests.dll
  