language: csharp
solution: Alt.Utils.sln
install:
  - nuget restore Alt.Utils.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - msbuild  /p:Configuration=Debug Alt.Utils.sln
  - ls
  - cd ./MaybeTests/bin/Debug/
  - ls
  - mono ./testrunner/NUnit.ConsoleRunner*/tools/nunit3-console.exe ./MaybeTests/bin/Debug/MaybeTests.dll
  